spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.74.44.242:3306/xinsilu?useUnicode=true&characterEncoding=utf-8
    username: xsl
    password: xsl
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enabled: true
      #additional-paths: demo/src/main/java
      exclude: WEB-INF/**
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    cache: false
mybatis:
  type-aliases-package: com.example.demo.pojo

server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
